# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam', '0002_auto_20170322_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friend',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
