# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam', '0007_auto_20170324_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belt_exam.User'),
        ),
    ]
